import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { PGlite } from '@electric-sql/pglite';
import { MARKETING_PLAN_STEPS, setupPlanItems, type ClientSetupInput } from './client-setup';
const migration = readFileSync(new URL('../migrations/064_client_split_setup.sql', import.meta.url), 'utf8');
const org = '00000000-0000-0000-0000-000000000010';
const user = '00000000-0000-0000-0000-000000000001';
const client = '00000000-0000-0000-0000-000000000020';
const input: ClientSetupInput = { requestId: client, organizationId: org, name: 'Mayas Construction', website: '', accountManagerId: '', onboardingDate: '2020-01-01', launchDate: '', seoHours: 5, template: 'foundation', customItems: [], scope: { version: 1, mode: 'monthly', hoursMode: 'committed', contentPieces: 1, gbp: true, gbpUsesSeoHours: false, listings: true, onboardingBudget: 'separate' } };
test('client, mixed content scope and SEO plan save atomically with tenant isolation and safe retries', async () => {
    const db = new PGlite();
    try {
        await db.exec(`create role authenticated; create role anon; create role service_role; alter default privileges grant execute on functions to anon; create schema auth;
            create function auth.uid() returns uuid language sql as $$select '${user}'::uuid$$;
            create table users(id uuid primary key, full_name text);
            create table organization_members(organization_id uuid, user_id uuid, role text);
            insert into users values ('${user}', 'Carlos'); insert into organization_members values ('${org}', '${user}', 'owner');
            create table clients(id uuid primary key, organization_id uuid, name text, domain text, account_manager_id uuid, account_manager_name text, launch_date date, seo_hours numeric, engagement_model text, status text, tier int, blogs_due_per_month numeric, campaign_end date, campaign_total_hours numeric);
            create table deliverable_commitments(id uuid default gen_random_uuid(), organization_id uuid, client_id uuid references clients(id), type text, title text, quantity_per_month numeric, cadence text, engagement_model text, starts_on date, is_active boolean, counts_toward_hours boolean, custom_fields jsonb);
            create table marketing_plans(id uuid default gen_random_uuid() primary key, organization_id uuid, client_id uuid references clients(id) unique, title text, steps jsonb);
            create table marketing_plan_items(marketing_plan_id uuid references marketing_plans(id), organization_id uuid, client_id uuid references clients(id), step_key text, title text, description text, priority text, sort_order int, is_custom boolean, roadmap_included boolean, roadmap_phase text check(roadmap_phase in ('onboarding','backlog')));
            grant usage on schema public, auth to authenticated; grant select, insert, update on all tables in schema public to authenticated;
        `);
        for (const table of ['clients', 'deliverable_commitments', 'marketing_plans', 'marketing_plan_items', 'organization_members']) await db.exec(`alter table ${table} enable row level security; create policy tenant on ${table} for all to authenticated using (organization_id = '${org}') with check (organization_id = '${org}');`);
        await db.exec(migration);
        await db.exec(readFileSync(new URL('../migrations/065_client_setup_permissions.sql', import.meta.url), 'utf8'));
        await db.exec('set role authenticated');
        const query = 'select create_client_with_setup($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) as id';
        const args = [client, org, input.name, null, user, input.onboardingDate, null, 5, input.scope, MARKETING_PLAN_STEPS, setupPlanItems(input)];
        const saved = await db.query(query, args);
        assert.deepEqual((await db.query(query, args)).rows, saved.rows);
        assert.equal((await db.query<{n: number}>('select count(*)::int n from clients')).rows[0].n, 1);
        const services = await db.query<{type: string; is_active: boolean; quantity_per_month: number}>('select type,is_active,quantity_per_month from deliverable_commitments');
        assert.equal(services.rows.length, 1); assert.equal(services.rows[0].type, 'Content'); assert.equal(services.rows[0].is_active, false);
        const items = await db.query<{n: number}>("select count(*)::int n from marketing_plan_items where roadmap_included and roadmap_phase = 'onboarding'"); assert.equal(items.rows[0].n, 3);
        await assert.rejects(db.query("update clients set status = 'active'"), /actual launched date/);
        await db.query("update clients set status = 'active', launch_date = '2020-02-01'");
        assert.equal((await db.query<{starts_on: string; is_active: boolean}>('select starts_on::text,is_active from deliverable_commitments')).rows[0].starts_on, '2020-02-01');
        assert.equal((await db.query<{is_active: boolean}>('select is_active from deliverable_commitments')).rows[0].is_active, true);
        await db.query("update clients set status = 'paused'"); assert.equal((await db.query<{is_active: boolean}>('select is_active from deliverable_commitments')).rows[0].is_active, false);
        const invalidItems = [{ ...setupPlanItems(input)[0], phase: 'invalid' }];
        await assert.rejects(db.query(query, ['00000000-0000-0000-0000-000000000021', ...args.slice(1,10), invalidItems]), /check constraint/);
        assert.equal((await db.query<{n: number}>('select count(*)::int n from clients')).rows[0].n, 1, 'failed plan insert rolls back the client and commitment');
        await assert.rejects(db.query(query, ['00000000-0000-0000-0000-000000000022', '00000000-0000-0000-0000-000000000011', ...args.slice(2)]), /cannot create clients/);
        await assert.rejects(db.query(query, ['00000000-0000-0000-0000-000000000023', org, input.name, null, '00000000-0000-0000-0000-000000000099', ...args.slice(5)]), /manager must belong/);
        await db.exec('reset role; set role anon'); await assert.rejects(db.query(query, args), /permission denied/);
    } finally { await db.close(); }
    assert.ok(readFileSync(new URL('../schema.sql', import.meta.url), 'utf8').includes(migration.trim()));
});
