import { MarketingPlanStep, MarketingPlanItemPriority } from './types';

export interface TemplateItem {
    stepKey: string;
    title: string;
    description: string;
    priority: MarketingPlanItemPriority;
}

export const MARKETING_PLAN_STEPS: MarketingPlanStep[] = [
    { key: 'setup', name: 'Introduction & Setup', sortOrder: 0 },
    { key: 'technical', name: 'Technical SEO', sortOrder: 1 },
    { key: 'research', name: 'Keyword & Competitor Research', sortOrder: 2 },
    { key: 'content', name: 'Content Audit & Creation', sortOrder: 3 },
    { key: 'onpage', name: 'On-page SEO', sortOrder: 4 },
    { key: 'links', name: 'Link Building', sortOrder: 5 },
    { key: 'local', name: 'Local SEO', sortOrder: 6 },
];

export const MARKETING_PLAN_TEMPLATE_ITEMS: TemplateItem[] = [
    // --- Step 1: Introduction & Setup -------------------------------------
    { stepKey: 'setup', priority: 'high', title: 'Confirm website and CMS access',
      description: 'Collect admin credentials for the website/CMS (WordPress, Shopify, etc.) and hosting. Verify we can edit pages, templates, and redirects.' },
    { stepKey: 'setup', priority: 'high', title: 'Connect Google Search Console',
      description: 'Verify the client\'s domain property in GSC and add our agency account. Confirm impressions/clicks data is flowing into the Analytics tab.' },
    { stepKey: 'setup', priority: 'high', title: 'Connect Google Analytics 4',
      description: 'Get admin or editor access to the GA4 property. Confirm the tracking tag fires on all pages and data appears in our nightly sync.' },
    { stepKey: 'setup', priority: 'high', title: 'Verify Google Business Profile access',
      description: 'Request manager access to the client\'s GBP listing(s). Confirm ownership, correct primary category, and that insights are visible.' },
    { stepKey: 'setup', priority: 'medium', title: 'Add client to Ahrefs tracking',
      description: 'Create the Ahrefs project, set target keywords for rank tracking, and run the first Site Audit crawl.' },
    { stepKey: 'setup', priority: 'high', title: 'Confirm conversion events and goals',
      description: 'Agree with the client on what counts as a conversion (calls, forms, purchases, bookings). Verify each event is tracked in GA4.' },
    { stepKey: 'setup', priority: 'low', title: 'Collect brand assets and guidelines',
      description: 'Gather logo files, brand colors, tone-of-voice notes, and any existing style guide for use in content and GBP posts.' },
    { stepKey: 'setup', priority: 'high', title: 'Hold kickoff call and set expectations',
      description: 'Walk the client through the plan, timeline, and communication cadence. Document commitments and open questions.' },

    // --- Step 2: Technical SEO ---------------------------------------------
    { stepKey: 'technical', priority: 'high', title: 'Run full site crawl',
      description: 'Run an Ahrefs Site Audit crawl of the entire site. Export the issues report and log the health score as the baseline.' },
    { stepKey: 'technical', priority: 'high', title: 'Fix crawl errors and broken links',
      description: 'Resolve 4xx/5xx errors, broken internal links, and redirect chains surfaced by the crawl. Re-crawl to confirm.' },
    { stepKey: 'technical', priority: 'high', title: 'Review robots.txt and XML sitemap',
      description: 'Confirm robots.txt isn\'t blocking important sections, the XML sitemap includes all indexable URLs, and it\'s submitted in GSC.' },
    { stepKey: 'technical', priority: 'medium', title: 'Check HTTPS and redirect health',
      description: 'Verify the site forces HTTPS, www/non-www resolves to one canonical host, and no mixed-content warnings exist.' },
    { stepKey: 'technical', priority: 'medium', title: 'Audit Core Web Vitals',
      description: 'Review LCP, INP, and CLS in GSC\'s Core Web Vitals report and PageSpeed Insights. List the top fixes for slow templates.' },
    { stepKey: 'technical', priority: 'medium', title: 'Check mobile usability',
      description: 'Test key templates on mobile. Fix viewport issues, tap-target spacing, and content wider than the screen.' },
    { stepKey: 'technical', priority: 'medium', title: 'Resolve duplicate content and canonicals',
      description: 'Identify duplicate or near-duplicate pages, set canonical tags correctly, and noindex thin utility pages.' },
    { stepKey: 'technical', priority: 'medium', title: 'Review site architecture and crawl depth',
      description: 'Ensure important pages are within 3 clicks of the homepage. Fix orphan pages by adding internal links.' },
    { stepKey: 'technical', priority: 'medium', title: 'Implement baseline schema markup',
      description: 'Add Organization/LocalBusiness schema sitewide plus appropriate types on key templates (Service, FAQ, Breadcrumb). Validate with Google\'s Rich Results test.' },

    // --- Step 3: Keyword & Competitor Research ------------------------------
    { stepKey: 'research', priority: 'high', title: 'Identify seed keywords from services',
      description: 'List every service/product the client offers and turn each into seed keywords, including local modifiers where relevant.' },
    { stepKey: 'research', priority: 'high', title: 'Build the keyword universe in Ahrefs',
      description: 'Expand seeds via Keywords Explorer (matching terms, questions, also-rank-for). Export with volume, difficulty, and intent.' },
    { stepKey: 'research', priority: 'medium', title: 'Map keywords to funnel stages',
      description: 'Tag each keyword as informational, commercial, or transactional so content types can be matched to intent.' },
    { stepKey: 'research', priority: 'high', title: 'Identify top competitors',
      description: 'Pick 3–5 true SERP competitors (who actually ranks for target keywords, not just business rivals).' },
    { stepKey: 'research', priority: 'medium', title: 'Run competitor content gap analysis',
      description: 'Use Ahrefs Content Gap to find keywords competitors rank for that the client doesn\'t. Shortlist high-value gaps.' },
    { stepKey: 'research', priority: 'medium', title: 'Run competitor backlink gap analysis',
      description: 'Compare backlink profiles against competitors in Ahrefs Link Intersect. Save referring domains that link to 2+ competitors.' },
    { stepKey: 'research', priority: 'high', title: 'Prioritize target keywords',
      description: 'Score the shortlist by business value, volume, and difficulty. Pick the primary targets for the first 90 days.' },
    { stepKey: 'research', priority: 'high', title: 'Create the keyword-to-page map',
      description: 'Assign every priority keyword to an existing page or a new page to be created. This map drives the content calendar.' },

    // --- Step 4: Content Audit & Creation -----------------------------------
    { stepKey: 'content', priority: 'medium', title: 'Inventory existing content',
      description: 'Export all indexable URLs with traffic, impressions, and top queries (GSC + GA4). This is the working sheet for the audit.' },
    { stepKey: 'content', priority: 'medium', title: 'Flag thin and outdated content',
      description: 'Mark pages with little traffic, outdated info, or under ~300 words for update, consolidation, or removal.' },
    { stepKey: 'content', priority: 'medium', title: 'Update or consolidate underperformers',
      description: 'Refresh outdated pages, merge overlapping ones with 301s, and prune dead weight. Track changes for before/after reporting.' },
    { stepKey: 'content', priority: 'high', title: 'Build the editorial calendar',
      description: 'Schedule the first 3 months of content from the keyword-to-page map, matched to the client\'s monthly blog commitment.' },
    { stepKey: 'content', priority: 'high', title: 'Improve core service page copy',
      description: 'Rewrite priority service pages: clear H1, benefit-led copy, trust signals, FAQ block, and strong call-to-action.' },
    { stepKey: 'content', priority: 'high', title: 'Publish the first blog batch',
      description: 'Write and publish the first set of blog posts from the calendar, each targeting one mapped keyword cluster.' },
    { stepKey: 'content', priority: 'medium', title: 'Add internal links from new content',
      description: 'Link every new post to its related service page and to 2–3 related posts using descriptive anchor text.' },
    { stepKey: 'content', priority: 'low', title: 'Set the content quality checklist',
      description: 'Document the pre-publish checklist (title tag, meta, headings, internal links, images, schema) so every post ships consistent.' },

    // --- Step 5: On-page SEO -------------------------------------------------
    { stepKey: 'onpage', priority: 'high', title: 'Optimize title tags and meta descriptions',
      description: 'Rewrite titles/metas on priority pages: primary keyword near the front, under pixel limits, compelling click reason.' },
    { stepKey: 'onpage', priority: 'medium', title: 'Audit heading structure',
      description: 'Ensure one H1 per page containing the target keyword, with a logical H2/H3 hierarchy — no skipped levels or styled-only headings.' },
    { stepKey: 'onpage', priority: 'low', title: 'Fix image alt text and compression',
      description: 'Add descriptive alt text to meaningful images and compress oversized files (WebP where possible).' },
    { stepKey: 'onpage', priority: 'medium', title: 'Review URL structure',
      description: 'Confirm URLs are short, keyword-relevant, and lowercase. Only change URLs where the win justifies a 301.' },
    { stepKey: 'onpage', priority: 'medium', title: 'Optimize internal anchor text',
      description: 'Replace generic anchors ("click here") pointing at priority pages with descriptive, keyword-relevant anchors.' },
    { stepKey: 'onpage', priority: 'medium', title: 'Add FAQ sections to key pages',
      description: 'Add 3–6 real customer questions with concise answers to service pages, marked up with FAQ schema.' },
    { stepKey: 'onpage', priority: 'low', title: 'Target featured snippets',
      description: 'Find queries where the client ranks 2–10 and a snippet exists. Restructure answers (definition, list, or table) to win the snippet.' },
    { stepKey: 'onpage', priority: 'high', title: 'Deep-audit the top 10 landing pages',
      description: 'Full on-page pass of the 10 most important pages: intent match, content depth, E-E-A-T signals, CTAs, and page experience.' },

    // --- Step 6: Link Building -----------------------------------------------
    { stepKey: 'links', priority: 'medium', title: 'Audit the baseline backlink profile',
      description: 'Review referring domains, anchor distribution, and authority trend in Ahrefs. Record baseline DR and referring-domain count.' },
    { stepKey: 'links', priority: 'low', title: 'Review for toxic links',
      description: 'Check for spammy link patterns. Only prepare a disavow if there\'s a genuinely manipulative profile — most sites don\'t need one.' },
    { stepKey: 'links', priority: 'medium', title: 'Build the citation and directory foundation',
      description: 'Submit consistent NAP to the core directories and relevant industry/local directories. Log each listing.' },
    { stepKey: 'links', priority: 'medium', title: 'Prospect from competitor link intersect',
      description: 'Work the saved link-intersect list: qualify each referring domain and add outreach-worthy ones to the pipeline.' },
    { stepKey: 'links', priority: 'medium', title: 'Build the outreach list and templates',
      description: 'Assemble target sites with contact info and write personalized outreach templates per link type (guest post, resource, mention).' },
    { stepKey: 'links', priority: 'high', title: 'Earn quality links monthly',
      description: 'Execute outreach with a target of 3–5 quality, relevant links per month. Log each acquired link with date and page.' },
    { stepKey: 'links', priority: 'low', title: 'Monitor new and lost backlinks',
      description: 'Review Ahrefs new/lost backlink alerts monthly. Reclaim valuable lost links and flag suspicious new ones.' },

    // --- Step 7: Local SEO -----------------------------------------------------
    { stepKey: 'local', priority: 'high', title: 'Complete the GBP profile',
      description: 'Fill every GBP field: description, services, hours, attributes, service areas, booking links. Completeness drives ranking.' },
    { stepKey: 'local', priority: 'high', title: 'Review GBP categories and services',
      description: 'Set the most specific primary category and add all relevant secondary categories. Mirror the service list to the website.' },
    { stepKey: 'local', priority: 'medium', title: 'Establish GBP photo and post cadence',
      description: 'Upload quality photos (exterior, interior, team, work examples) and schedule recurring GBP posts (offers, updates, projects).' },
    { stepKey: 'local', priority: 'high', title: 'Launch the review generation strategy',
      description: 'Set up the review ask workflow (post-job SMS/email with direct review link). Target a steady flow of new Google reviews.' },
    { stepKey: 'local', priority: 'medium', title: 'Respond to all reviews',
      description: 'Reply to every review — thank positives, address negatives professionally. Keep response time under one week.' },
    { stepKey: 'local', priority: 'medium', title: 'Audit NAP consistency',
      description: 'Verify name, address, and phone are identical across the website, GBP, and all citations. Fix mismatches.' },
    { stepKey: 'local', priority: 'high', title: 'Build local landing pages',
      description: 'Create a dedicated page per priority service-area/city with unique local content — no doorway-page boilerplate.' },
    { stepKey: 'local', priority: 'medium', title: 'Track local pack rankings',
      description: 'Add priority "service + city" keywords to rank tracking and monitor local pack presence monthly.' },
];
